//! A second, clipped Bevy camera that provides a solar-system overview.
//!
//! The game is drawn with gizmos rather than sprites, so using another camera
//! is both cheaper and more faithful than maintaining a second set of map
//! markers. It also keeps the minimap available on native and in the web build
//! without introducing Bevy UI underneath the panel-kit DOM overlay.

use crate::{game::Lander, terrain::TerrainData, GameState};
use bevy::{
    prelude::*,
    render::camera::{ClearColorConfig, ScalingMode, Viewport},
    render::view::RenderLayers,
    window::PrimaryWindow,
};

const MAP_WIDTH: u32 = 280;
const MAP_HEIGHT: u32 = 190;
const MAP_MARGIN: u32 = 18;
const MAP_PADDING: f32 = 1.15;

pub struct MinimapPlugin;

impl Plugin for MinimapPlugin {
    fn build(&self, app: &mut App) {
        // Web renders the system map as a real panel-kit SVG panel. Native
        // retains the clipped second Bevy camera implementation.
        #[cfg(target_arch = "wasm32")]
        let _ = app;
        #[cfg(not(target_arch = "wasm32"))]
        app.add_systems(
            Update,
            (
                spawn_minimap,
                sync_body_markers,
                update_minimap,
                toggle_minimap,
            )
                .chain()
                .run_if(in_state(GameState::Playing)),
        )
        .add_systems(OnExit(GameState::Playing), cleanup_minimap);
    }
}

#[derive(Component)]
pub(crate) struct MinimapCamera;

#[derive(Component)]
struct MinimapBodyMarker(usize);

/// Spawn lazily in `Update`: this guarantees the terrain generated by the
/// game's `OnEnter(Playing)` system is already visible.
fn spawn_minimap(mut commands: Commands, existing: Query<(), With<MinimapCamera>>) {
    if !existing.is_empty() {
        return;
    }

    commands.spawn((
        Camera2d,
        Camera {
            order: 10,
            clear_color: ClearColorConfig::Custom(Color::srgba(0.015, 0.025, 0.055, 0.90)),
            // panel-kit owns the DOM UI; this camera should never render Bevy UI.
            is_active: true,
            ..default()
        },
        Projection::Orthographic(OrthographicProjection {
            near: -1000.0,
            far: 1000.0,
            ..OrthographicProjection::default_2d()
        }),
        Msaa::Off,
        RenderLayers::from_layers(&[0, 1]),
        MinimapCamera,
        Name::new("Solar-system minimap camera"),
    ));
}

/// Bodies retain their physical sizes in the world. At system scale those can
/// be smaller than one minimap pixel, so map-only markers provide a selectable
/// visual target without changing any gravitational radius or mass.
fn sync_body_markers(
    mut commands: Commands,
    terrain: Res<TerrainData>,
    existing: Query<(Entity, &MinimapBodyMarker)>,
) {
    if !terrain.is_changed() && !existing.is_empty() {
        return;
    }

    let system_extent = terrain
        .planets
        .iter()
        .map(|body| body.center.length() + body.radius)
        .fold(1_000.0_f32, f32::max);
    let marker_size = (system_extent * 0.012).clamp(160.0, 2_400.0);

    for (entity, marker) in &existing {
        let Some(body) = terrain.planets.get(marker.0) else {
            commands.entity(entity).despawn();
            continue;
        };
        commands.entity(entity).insert((
            Transform::from_translation(body.center.extend(20.0)),
            Sprite {
                color: body.surface_color,
                custom_size: Some(Vec2::splat(marker_size)),
                ..default()
            },
        ));
    }

    let existing_count = existing.iter().count();
    for (index, body) in terrain.planets.iter().enumerate().skip(existing_count) {
        commands.spawn((
            Sprite {
                color: body.surface_color,
                custom_size: Some(Vec2::splat(marker_size)),
                ..default()
            },
            Transform::from_translation(body.center.extend(20.0)),
            RenderLayers::layer(1),
            MinimapBodyMarker(index),
            Name::new("Minimap body marker"),
        ));
    }
}

fn update_minimap(
    windows: Query<&Window, With<PrimaryWindow>>,
    terrain: Res<TerrainData>,
    lander: Query<&Transform, (With<Lander>, Without<MinimapCamera>)>,
    mut map: Query<(&mut Camera, &mut Transform, &mut Projection), With<MinimapCamera>>,
) {
    let Ok(window) = windows.single() else { return };
    let Ok((mut camera, mut transform, mut projection)) = map.single_mut() else {
        return;
    };

    let physical_width = window.physical_width();
    let physical_height = window.physical_height();
    let width = MAP_WIDTH.min(physical_width.saturating_sub(MAP_MARGIN * 2));
    let height = MAP_HEIGHT.min(physical_height.saturating_sub(MAP_MARGIN * 2));
    if width < 32 || height < 32 {
        camera.is_active = false;
        return;
    }

    camera.viewport = Some(Viewport {
        // Bevy viewport coordinates start at the upper-left.
        physical_position: UVec2::new(
            physical_width.saturating_sub(width + MAP_MARGIN),
            MAP_MARGIN,
        ),
        physical_size: UVec2::new(width, height),
        depth: 0.0..1.0,
    });

    // Fit every planet (including its radius), and include the lander if it has
    // travelled outside that box. This remains valid as orbital motion updates
    // planet centers later.
    let mut min = Vec2::splat(f32::INFINITY);
    let mut max = Vec2::splat(f32::NEG_INFINITY);
    for planet in &terrain.planets {
        let radius = Vec2::splat(planet.radius);
        min = min.min(planet.center - radius);
        max = max.max(planet.center + radius);
    }
    if let Ok(lander) = lander.single() {
        let position = lander.translation.truncate();
        min = min.min(position - Vec2::splat(40.0));
        max = max.max(position + Vec2::splat(40.0));
    }
    if !min.is_finite() || !max.is_finite() {
        return;
    }

    let center = (min + max) * 0.5;
    let extent = (max - min).max(Vec2::splat(100.0)) * MAP_PADDING;
    let aspect = width as f32 / height as f32;
    let visible_height = extent.y.max(extent.x / aspect);

    transform.translation = center.extend(999.0);
    if let Projection::Orthographic(orthographic) = projection.as_mut() {
        orthographic.scaling_mode = ScalingMode::Fixed {
            width: visible_height * aspect,
            height: visible_height,
        };
    }
}

/// `M` is intentionally handled by Bevy rather than the DOM so the same
/// shortcut works in native builds and whenever the canvas has focus on web.
fn toggle_minimap(
    keyboard: Res<ButtonInput<KeyCode>>,
    mut map: Query<&mut Camera, With<MinimapCamera>>,
) {
    if keyboard.just_pressed(KeyCode::KeyM) {
        if let Ok(mut camera) = map.single_mut() {
            camera.is_active = !camera.is_active;
        }
    }
}

fn cleanup_minimap(
    mut commands: Commands,
    maps: Query<Entity, Or<(With<MinimapCamera>, With<MinimapBodyMarker>)>>,
) {
    for entity in &maps {
        commands.entity(entity).despawn();
    }
}
